source/faucet/main.d

```
The solution is simply to skip the UTXOs which would cause the assert.
However we'll soon run into another problem - we'll run out of UTXOs.
```
Also contains a submodule update that has been deployed live already.

Fix issue #5 - The tool assert(0) on count > 10

---

source/faucet/main.d

The `updateUTXOCache` function is now available to the `TestUTXOSet`.
This clears used `UTXO`s in addition to adding new ones.
Fixed by #10, [agora#1318](https://github.com/bpfkorea/agora/pull/1318)

Use `updateUTXOCache` instead of `put`

---

source/faucet/main.d

Now that we have [agora#1345](https://github.com/bpfkorea/agora/pull/1345), a helper function can be implemented. It takes a range of `Output`s and merges them into a range of `Transaction` with a single `Input` and `Output`.
Example use-case: Whenever we have more than 200 `UTXO`s, call this function until we have less than 200.
After the function has been finalized, I will include it in the `send` process, with an appropriate bound.
Fixes #14

Implement function to merge UTXOs 

---

dub.json

The `DataPayload` parameter is necessary for `Transaction` to be sent properly.

Update faucet to support DataPayload

---

source/faucet/main.d

The `mergeTx` function was creating the same number of `Output`s as `Input`s so it was not actually merging.
We decide to either split or merge based on the number of `UTXO`, and these functions adjust the number. Merging should decrease the number of `UTXO` by definition as below :
```
[main(J2TR) INF] UTXO delta: -15
```
The most basic way (current implementation) is to create a single `Transaction` with multiple `Input`s and a single `Output`.
Also, `filter` should have been called in `splitTx` instead of `mergeTx`. Its role is to skip splitting `Output`s with `Amount` less than `count` so we don't end up with `Amount(0)`.

Update functions to merge transactions properly

---

source/faucet/api.d
source/faucet/main.d

The basic structure of a `Faucet API` has been implemented.
Faucet should expose a basic API so it can be called from a frontend service (website) to make `Transaction`s.
`getUTXOs` performs a HTTP `GET /utxos` and returns an array of all UTXOs known.
Part of faucet #15

Implement a basic API

---

source/faucet/api.d
source/faucet/main.d

`Faucet` should expose a basic API so it can be called from a frontend service (website) to make `Transaction`s.
The endpoint `POST /send?recv=KEY&amount=1234` sends `amount` BOA to `KEY`, using owned UTXOs.
The API picks one owned UTXO from the storage. If `amount`  <= `UTXO` amount then the `amount` is [drawn](https://github.com/bpfkorea/agora/blob/b6c7b12b9c8dc3fbc88f6e3f8c8dbefd29af5a08/source/agora/utils/Test.d#L529). 
If `amount` > `UTXO` amount then a new `UTXO` is attached and drawn. This repeats until there is a remainder.
Part of #15

 Expose `sendTransaction` endpoint

---

.github/workflows/main.yml

Significant whitespace was a wonderful idea.

Fix syntax error in Github CI configuration

---

Dockerfile

This update includes the refactoring of the crypto module.
`alpine:3.12` uses `ldc-1.20.1` which is no longer compliant with `agora`. We build with `agora-builder` instead.

Update submodules to the latest version

---

source/faucet/api.d
source/faucet/main.d

The interface name has been changed to use `API`.

Trivial: Update API names

---

dub.json

The GenesisBlock and the Wellknownkeys will change so we need Faucet to also use the correct agora submodule version.
Last commit will need to be updated to use v0.x.x agora with changes after https://github.com/bosagora/agora/pull/1778 is merged.

Update Agora submodule to use the latest Well Known Keypairs

---

source/faucet/main.d

Soon this number is going to change and be less,
so computer it instead of hardcoding it.

Remove assumption about number of well-known keypairs

---

source/faucet/main.d

The number of the well-known keypairs is used in various places, so it has been made global.

Make `KeyCount` global

---

source/faucet/main.d

The number of UTXOs being split and merged has been constant so far.
Now it is dynamic in order to add randomness.

Make the number of UTXOs during split and merge dynamic

---

source/faucet/main.d

The previous commit didn't increment the right value,
leading to the same 20 blocks being endlessly fetched.

Fix catchup when there are more than 20 blocks

---

source/faucet/main.d

The actual `Amount` that is sent is 10,000,000 times the original amount.
This amount includes the number of "cents".
This is similar to [`AmountFmt` in `PrettyPrinter`](https://github.com/bosagora/agora/blob/68df58ee57851017ccbd73da1b4c98000088a672/source/agora/utils/PrettyPrinter.d#L141-L170)

Use correct amount in `sendTransaction`

---

source/faucet/main.d

This is necessary when listening and responding to requests.
Locally, one can `curl http://127.0.0.1:9113/metrics`.
Part of #65

StatsServer: Listen to requests on stats port

---

source/faucet/main.d

A recent PR removed the lockstep approach of Faucet,
where we would wait for a block to be generated until we sent new transactions.
However, the initialize 'setup' phase was kept. Since the setup has also be fixed
to be always performed (if not done yet) when the 'send' timer is called,
we can just remove this special case now.

Do not wait until first block to keep sending txs

---

source/faucet/main.d

Since splitTx does 'filter', we could end up in a situation where
every transaction was filtered out and Faucet would just stall.
Since ranges are lazy, and splitTx returns a range, we can simply
call 'take' on the return value.

Use 'take' on the return of splitTx, not its input

---

source/faucet/main.d

Use `isPayment` for `tx`
Agora will soon be updated to specify the transaction type for each output.  
A new function `isPayment` will determine the transaction type.
This updates Faucet to use the new function.
Related to https://github.com/bosagora/agora/pull/2114

Update Faucet to use `isPayment` in preparation for Agora update

---

.dockerignore
dub.json

So the integration test of Agora was failing because we were missing some of dub's magic.
Added it, and got the weirdest error, because the `faucet` binary which I had locally built was copied to the container verbatim. Added a dockerignore for that, then realized that the reason it was not overwritten was that adding `configuration` made `dub` infers the package as a library... And here we are. And while I was at it, added the export dynamic thing we have in Agora, because stacktraces are good.

Fix `dub.json` to actually initialize the Vibe.d event loop (+ dockerignore)

---

dub.json
source/faucet/main.d

Fix a few places where the `WK.Keys` were still used even though the config file was providing the keys to use.

Fix the behavior when using the config yaml

---

source/faucet/main.d

Since the default values are used when the config file does not exist, there are no errors.
We now always use a config file, so this condition below is not needed.
```D
if (configPath == "none" || !configPath.exists)
```

Remove condition with no config file

---

source/faucet/config.d
source/faucet/main.d

The whole config was being dumped which would include the key seeds.
To prevent the keys being logged the `toString` is overridden to skip
logging the keys.

Do not log the key seeds at startup

---

source/faucet/main.d

Merging transaction was broken on multiple levels:
- First, the range was consumed multiple times, as it was both mapped and zipped;
- Second, and foremost, we were passing PublicKey as the UTXO hash, which obviosusly didn't work;
This commit fixes both and hopefully makes the code easier to follow.

TxGen: Fix merging transaction

---

doc/config.local_single.yaml
source/faucet/main.d

Currently when the Faucet merges `utxo` to create a `Transaction` with multiple `inputs` and a single `output` Agora rejects the tx with `Rejected tx. Reason: LockType.Key signature in unlock script failed validation.`
This current commits do not fix it but might help.

A few small updates to help with solving the `tx rejected` issue

---

source/faucet/main.d

```
Previously, the condition was only true when the user passed --bind=value
on the command line, but should also be true if something is configured
in the config file.
```

Web interface: Start it when configured via config file

---

Dockerfile
source/faucet/main.d

The `frontend` folder was not bound properly, so the `index.html` was unable to be found.
Therefore, we use `/usr/share/faucet/frontend/`.

Frontend: Correct Docker image setup

---

source/faucet/api.d
source/faucet/main.d

In the faucet frontend, the amount of coins sent is fixed.
There is no need for an `amount` parameter.
Fixes #105

Remove `amount` parameter from `sendTransaction` endpoint

---

frontend/index.html
frontend/styles.css
source/faucet/api.d
source/faucet/main.d

- If we use `jQuery` and `Ajax`, we can send coins using the correct `HTTP` method and `Content-Type`.
- The frontend now shows a validation message below the input field, depending on the given address.
1st commit pair-programmed w/ @ferencdg  
Fixes #106

Frontend: Send coins using jQuery and Ajax

---

frontend/index.html

Previously the error message shown on the web page on failure was hardcoded to `Invalid address`. 
Now the error message returned in the json response from the Faucet is used.

Issue116: display relevant errors in webpage when fails to send boa

---

source/faucet/main.d

Attempting to send coins without any `UTXO` or with one `UTXO` results in an assertion error.
The faucet now checks the number of `UTXO`s before sending and prevents sending if there is less than one.
Fixes #115

Prevent sending coins when there is less than one UTXO

---

source/faucet/main.d

It asserts in case of error, and is going to be removed.
Use 'add' instead.

Do not use Amount.mustAdd

---

source/faucet/main.d

This is to match the changes in [4b568c](https://github.com/bosagora/agora/commit/4b568c56ff02ddb44cfc20a35726dbcf1987a386).
Fixes:
```
Rejected tx. Reason: LockType.Key signature in unlock script failed validation.
```

Get the challenge hash of the transaction in `keyUnlocker`

---

source/faucet/main.d

Transition from the `deprecated` `sign` to the new `sign`.
Also includes a commit which filters `Amount`s less than `5,000,000`.
Smaller coin units should be filtered, so that there is enough amount in the output for the fee deduction.
Part of #26

Use updated `sign` method

---

source/faucet/main.d

It showed 0 because the calculation was wrong.
Now, the average amount is calculated properly.
```
[main(k/Y/) INF]    UTXO set: 16 entries
[main(k/Y/) INF]    Median: 304999999906200, Avg: 304999999906200
[main(k/Y/) INF]    L: 304999999906200, H: 304999999906200
```
Fixes #129

Fix calculation of average amount in `send` method

---

source/faucet/main.d

Recently in PROD env it has been required that the Faucet is restarted
as it can get into a state where it filters out all sent utxos and none
remain. The restart clears the sent_utxo and it then resumes ok. This
fix will clear the sent_utxo when no more utxo are available. It might
cause some double spend but at least it will continue to send txs.

Prevent need to restart Faucet

---

source/faucet/main.d

Split `owned utxo` if `owned utxo` are less than threshold otherwise merge `owned utxo`s. 
By `owned utxo` we mean those that the  faucet has the private key for so can sign.

Issue153 fix merge or split logic

---

doc/config.example.yaml
source/faucet/main.d

This adds some useful logging so that if PROD gets stuck we can see what Faucet sent to the nodes in terms of number of transactions and the total byte size.

Log the number and size of transactions to be sent

---

.gitmodules

This doesn't work for everyone, and is not required,
since the actions have a mean to specify recursive fetch.
It's mostly problematic because depth can't be specified,
so it triggers errors on Makd, a submodule of Ocean,
but not one of Agora.

Remove fetchRecurseSubmodules from configuration

---

source/faucet/main.d

If we slow down the tx generator, or we disable it, Faucet will no longer
update its state, and will eventually run out of UTXOs.

Make updating the state independent of the tx generator

---

source/faucet/main.d

Display reason in frontend when `postTransaction` fails

---

source/faucet/main.d

Assuming that network is out of TXs to externalize
and our sent_utxos list is out-of-sync.

Clear sent_utxos on zero TX blocks

---

source/faucet/main.d

The public import will be removed in agora submodule in a later commit.

Import TxBuilder
