source/faucet/main.d

```
Because the fix to bpfk/agora#1286 we needed to keep
a list of transactions around.
Now that this issue has been fixed, we can greatly simplify
and improve the code by relying solely on UTXOs.
This also improves the setup and send functions.
```

Update Faucet to only use UTXOs to drive itself

---

source/faucet/main.d

The main thing here are the stats, and the fact that Faucet's output is now readable.
I have some more change locally to update the behavior, but forgot to pull before doing them 🤦

Minor code and usability improvements

---

source/faucet/main.d

The `API client` is declared in the constructor of the class, so that it can be used in the API endpoints.

Refactoring: set the client within the constructor

---

.github/workflows/main.yml
dub.json
dub.selections.json

@bpfkorea/core  I can't get this to work properly with the latest `v0.x.x` agora nodes.
Faucet sends 8 transactions and the receiving node accepts them, but then the node fails to nominate anything.
I think v0.x.x is broken..

Upgrade Agora submodule + vibe.d

---

.gitmodules
dub.json
dub.selections.json
source/faucet/api.d

This submodule update includes the refactoring of crypto related modules.

Update Agora submodule to the latest commit

---

source/faucet/main.d

```
We are seeing issues in the system integration tests where Faucet
starts before the Agora node is ready to accept requests.
This leads to Faucet exiting and the test failing.
Similar issue might manifest in the live system if faucet
is deployed in parallel of the nodes it contact.
```
Better reviewed with whitespace changes off.

Make the setup retry indefinitely

---

.gitignore

This one is compatible with agora for https://github.com/bpfkorea/agora/pull/1693

Latest submodules

---

source/faucet/api.d
source/faucet/main.d

Faucet listens to HTTP requests so that the endpoints can be called.
Solves #27

Listen to HTTP requests

---

dub.json

Want to make sure it works before I merge https://github.com/bosagora/agora/pull/1892.

Update Agora submodule

---

source/faucet/main.d

```
If Faucet restarts while the network has been up for a long time,
it will catch up by downloading all the blocks.
However it will only be able to fetch 20 blocks per query
(a node-side limit to prevent DoS), and will not retry
until the next timer triggers.
This means that if it has to catch up to 200 blocks for example,
it will take 200 / 20 * 30s = 300s, or 5 minutes.
```

Catchup: Block until we have caught up

---

Dockerfile

PR68 forgot to do this, so Faucet would always fail to start.

Copy frontend files into Docker image

---

source/faucet/main.d

See each commit for the motivation.

Make binding to an interface configurable and optional + always send txs

---

source/faucet/main.d

Found a couple issues in the process, see the first two commits.

Fix #72: Provide our own event handler to gracefully shut down

---

dub.json
source/faucet/config.yaml
source/faucet/main.d

Faucet can read a config file and store the keys in the Config struct.
Fixes #37

Read non well-known keys from a config file

---

source/faucet/main.d

See each commit, require to unbreak agora.

Add support for configuration config file (including a 'none' one)

---

source/faucet/main.d

Updated to use `cycle` on the `range` of keys so we can still use desired count as it will just wrap around the `range`.

Fix bug in `splitTx` function

---

source/faucet/main.d

The `Builder` `struct` was created with the intention of making it
easier to override the `unlocker` used in the signing of `transactions`.
This is now required as we are not always using the `well known keys`
from the source file but can provide keys in the config file.
However the `Builder` `struct` had a bug which meant that the `sign` was
not being called when intended.
This now uses an alternative way which still uses the TxBuilder `sign`
function but calls with a new `unlocker` delegate.

Use TxBuilder directly again

---

source/faucet/main.d

Also use the non-deprecated 'sign' method of TxBuilder.

Update Agora to the latest commit

---

source/faucet/config.d
source/faucet/main.d

Update Agora to v0.20.0

---

.gitmodules
dub.json
dub.selections.json

This is needed in order to introduce it into Agora.
See bosagora/agora#2509

Add unused 'config' submodule

---

dub.json

Nothing good happens after 2AM.

Fix missing 'source' component in dub.json

---

source/faucet/main.d

This first PR will probably not fix it but it addresses a couple of problems and maybe helps.

Part of Issue145: Prevent need to restart Faucet to correct utxo set.

---

frontend/index.html

Prevent bots from draining the utxo from the Faucet web page.

Add Google ReCaptcha checkbox

---

dub.json
dub.selections.json

This is just to clean up submodules that are no longer at the top level.

Update top level `dub.selections.json` to exclude submodules below `agora`

---

source/faucet/config.d
source/faucet/main.d

```
The parsing code in Faucet predates the `config` library.
It wasn't switched over originally as `config` lacked some features
required for it to happen, but the latest version now covers all our needs.
```
Depends on https://github.com/bosagora/config/pull/21 being merged and the Agora submodule being updated.

Switch configuration parsing to Config framework

---

source/faucet/config.d
source/faucet/main.d

```
As we are using more and more of Agora, we will increasingly need the ability
to configure Loggers for its subsystem (e.g. the Ledger logger, when introduced).
Hence a good step forward is to parse the logging configuration as Agora does,
and to use a logger in our main.
```

Use Ocean's Logger instead of Vibe.d

---

source/faucet/api.d
source/faucet/config.d
source/faucet/main.d

Use a Ledger instead of a bare UTXOSet

---

frontend/index.html
frontend/styles.css
source/faucet/api.d
source/faucet/main.d

Fixes #171 and some OCDs
- > Also the right alignment instead of center on the CAPTCHA
- Hides amount field, its just confusing
- Adds new API, `/stake`
- Adds new button `Create Validator Stake`
- Adds information tooltips to buttons

Add validator stake creation functionality

---

doc/config.local_single.yaml

Just a trivial config file update, nothing important

Trivial: Remove invalid keys from example config

---

source/faucet/main.d

Multiple refactorings: Reduce scope of variable and simplify the code

---

source/faucet/main.d

to provide detailed error messages
Fixes #136 
This [uses error handler](https://github.com/bosagora/agora/blob/83349fdb578db05709b165ca9f045a57f23ba18c/source/agora/node/Runner.d#L450-L482) from Agora.

Use `Exception.message` instead of `Exception.msg`

---

source/faucet/main.d

Merge at the rate we split

---

source/faucet/main.d

Send multiple merge TXs per timer tick

---

doc/config.local_single.yaml
source/faucet/main.d

A refactor to use the updated method for setting up the TxBuilder from Agora.

Update Faucet to use updated Tx builder from Agora
